### ISSUE TITLE
Problem with launching FASMA

### ISSUE THREAD

**Issue by AlexSokokoliuk** [MariaTsantaki/FASMA-synthesis#21]
```
alex@alex-System-Product-Name:~/Downloads/FASMA-synthesis-master$ fasma
Traceback (most recent call last):
  File "/home/alex/.local/bin/fasma", line 12, in <module>
    driver = FASMA.FASMA(cfgfile=cfgfile, overwrite=None)
  File "/home/alex/.local/lib/python3.8/site-packages/FASMA/synthDriver.py", line 50, in __init__
    self.synthdriver()
  File "/home/alex/.local/lib/python3.8/site-packages/FASMA/synthDriver.py", line 526, in synthdriver
    for (self.initial, self.options) in self._genStar():
  File "/home/alex/.local/lib/python3.8/site-packages/FASMA/synthDriver.py", line 110, in _genStar
    with open(self.cfgfile, 'r') as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yml'
```

**Comment by DanielAndreasen** [comment]
It seems like you are trying to run `fasma` from a folder, where there is no `config.yml`. You can use this as an example: https://github.com/MariaTsantaki/FASMA-synthesis/blob/master/FASMA/config.yml

**Comment by DanielAndreasen** [comment]
Hi @AlexSokokoliuk, did you manage to make `fasma` run?

**Comment by AlexSokokoliuk** [comment]
Yes, now all is OK.
