### ISSUE TITLE
 No such file or directory: 'summary.out'

### ISSUE THREAD

**Issue by AstroSong** [MariaTsantaki/FASMA-synthesis#22]
Hi guys,

When I run "fasma", It doesn't produce a file called summary.out.

When I install the fasma using install_fasma.sh, it stops when it compiles the install_fasma.sh, the error is:

Moogsilent.f:21:72:

   21 |       moogpath =
      |                                                                        1
Error: Invalid character in name at (1)
make: *** [Moogsilent.o] Error 1
MOOGSILENT is not installed properly!

But when I pick out the sentence "make -C FASMA/MOOG/ -f Makefile.maclapsilent clean ; make -C FASMA/MOOG/ -f Makefile.maclapsilent" and run it, there is no error. 

I do not know whether the lack of summary.out is caused by the installation.

**Comment by sagiph-weizmann** [comment]
Identical to issue #22.

The solution suggested seems to complete the installation successfully ('make -C FASMA/MOOG/ -f Makefile.maclapsilent clean ; make -C FASMA/MOOG/ -f Makefile.maclapsilent'), but I also do not get the summary.out file.

When running test_FASMA.py, I get the following termination:
_Line list: ../rawLinelist/elements.lst
Intervals list: ../rawLinelist/intervals_elements.lst
Traceback (most recent call last):
  File "test_FASMA.py", line 48, in <module>
    r.test_minimization_values()
  File "test_FASMA.py", line 29, in test_minimization_values
    r = FASMA(**options)
  File "/Users/benamis/opt/anaconda3/lib/python3.8/site-packages/FASMA/synthDriver.py", line 50, in __init__
    self.synthdriver()
  File "/Users/benamis/opt/anaconda3/lib/python3.8/site-packages/FASMA/synthDriver.py", line 534, in synthdriver
    self._prepare()
  File "/Users/benamis/opt/anaconda3/lib/python3.8/site-packages/FASMA/synthDriver.py", line 163, in _prepare
    self.ranges, atomic = read_linelist_elem(
  File "/Users/benamis/opt/anaconda3/lib/python3.8/site-packages/FASMA/synthetic.py", line 424, in read_linelist_elem
    atomic = atomic.append(a)
  File "/Users/benamis/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'_

When running FASMA, I get the following:
Traceback (most recent call last):
  File "/Users/benamis/opt/anaconda3/bin/fasma", line 12, in <module>
    driver = FASMA.FASMA(cfgfile=cfgfile, overwrite=None)
  File "/Users/benamis/opt/anaconda3/lib/python3.8/site-packages/FASMA/synthDriver.py", line 50, in __init__
    self.synthdriver()
  File "/Users/benamis/opt/anaconda3/lib/python3.8/site-packages/FASMA/synthDriver.py", line 534, in synthdriver
    self._prepare()
  File "/Users/benamis/opt/anaconda3/lib/python3.8/site-packages/FASMA/synthDriver.py", line 184, in _prepare
    self.xspec, self.yspec = func(
  File "/Users/benamis/opt/anaconda3/lib/python3.8/site-packages/FASMA/utils.py", line 557, in fun_moog_synth
    x_synth, y_synth = _read_raw_moog('summary.out')
  File "/Users/benamis/opt/anaconda3/lib/python3.8/site-packages/FASMA/synthetic.py", line 284, in _read_raw_moog
    with open('summary.out', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'summary.out'

And suggestions ?
